### ISSUE TITLE
Export blendMode type?

### ISSUE THREAD

**Issue by nickpeihl** [elastic/ems-client#110]
The ems-client library defines the `blendMode` type, but we don't have an export for the array. So in Kibana, I'm creating an array of strings of the supported blend types, but Typescript is angry because the `TMSService.transformColorProperties` method expects the `operations` argument to be of type `blendMode` rather than `string`.

Do we need to export the type in `index.ts`, (e.g. `export type { blendMode } from './utils';`) or am I doing something incorrectly?

**Comment by jsanz** [comment]
You are totally right. I did not got affected by this issue because Landing Page is not yet in TypeScript and I could use any value for the method.
