### ISSUE TITLE
Rename TMS styles

### ISSUE THREAD

**Issue by jsanz** [elastic/ems-client#125]
Following up from elastic/kibana#136642, EMS Client is responsible to provide names to the basemap styles with this function.

https://github.com/elastic/ems-client/blob/8125d8e6c0d3d062b40bb2639de4e548cf77471d/src/tms_service.ts#L371

This is just trying to translate the name of the style provided at the service level in the manifest.

So I see two options:

1. Change the names at the service level. We would need to investigate how difficult would be to version the tile manifests, as it is (I think) just validating the version component of the url.

3. Change the names here at `ems-client`, so this affects only the future releases. This is easier to maintain but couples our styles with the client, which in some ways already happen with the work we did to modify the styles on the fly (labels and color blending).

@nyurik @nickpeihl what do you think?

**Comment by nickpeihl** [comment]
I think the least disruptive thing we can do is version the tile manifest. Kibana is [tightly coupled to the service names](https://github.com/elastic/kibana/blob/c0edeb9abfed19b62c8d609cf9bdfac984014907/src/plugins/maps_ems/common/ems_defaults.ts#L15-L17). 

However versioning the tile manifest will require a bit more backend work. But I think it would be beneficial in the long run, especially as we make style improvements such as https://github.com/elastic/osm-bright-desaturated-gl-style/pull/5 that we might only want to deploy for future releases rather than all releases.

**Comment by jsanz** [comment]
> Kibana is [tightly coupled to the service names](https://github.com/elastic/kibana/blob/c0edeb9abfed19b62c8d609cf9bdfac984014907/src/plugins/maps_ems/common/ems_defaults.ts#L15-L17).

Well, those are the identifiers. The names are obtained from the `getDisplayName` function and they can be overridden at the client without (apparent) issues for both EMS Landing Page and Kibana.

![image](https://user-images.githubusercontent.com/188264/180751564-c6513bd0-be27-40e2-8977-1017fc8e8120.png)

![image](https://user-images.githubusercontent.com/188264/180750793-744d2329-9161-485d-a3bb-7ce27ed45833.png)


> However versioning the tile manifest will require a bit more backend work. But I think it would be beneficial in the long run, especially as we make style improvements such as [elastic/osm-bright-desaturated-gl-style#5](https://github.com/elastic/osm-bright-desaturated-gl-style/pull/5) that we might only want to deploy for future releases rather than all releases.

Indeed. It's interesting that we've been OK without versioning our tile manifest for quite a long time, but now we have hit two different, and very valid, use cases.

I'll keep this open as for now but given that this is not a hard pressing issue, we better start working on the infra side to get versioning for our tile manifest. Thanks @nickpeihl for your comments!

**Comment by jsanz** [comment]
Closing as per https://github.com/elastic/kibana/issues/136642
