### ISSUE TITLE
Expand semver compatibility?

### ISSUE THREAD

**Issue by spalger** [elastic/ems-client#76]
https://github.com/elastic/ems-client/blob/0ff4734a63412eb28600725a60ba7bec7814f823/package.json#L44

Is there a reason that semver is limited to the single `7.3.2` version? I'm just trying to deduplicate some installed packages and this is leading to some duplication in Kibana.

**Comment by nickpeihl** [comment]
@spalger `@elastic/ems-client@v7.15.1` has been published to NPM.
